### ISSUE TITLE
Handle XDebug 3 configuration better

### ISSUE THREAD

**Issue by NicoHaase** [dvdoug/behat-code-coverage#1]
I've just found your package and fell in love immediately. But there's one more thing I'd like to see: on my local machine, I run Behat tests before commiting. Sometimes, I have to debug them using XDebug. With the extension enabled, this fails, as I usually don't run XDebug in coverage mode, and the driver throws an exception for this in https://github.com/sebastianbergmann/php-code-coverage/blob/0b4ce85a86040303d93beddf4f31f2ab07775e9a/src/Driver/Xdebug3Driver.php#L65.

You properly catch errors based on `SebastianBergmann\CodeCoverage\NoCodeCoverageDriverAvailableException` (when absolutely no driver is available), but I think you could extend the catch block with `SebastianBergmann\CodeCoverage\Driver\Xdebug3NotEnabledException`. This could help to always enable the extension and run whenever possible. In case of any error, display an information like "No code coverage driver is available" or "Code coverage driver not configured properly", but keep on running the testsuite

**Comment by dvdoug** [comment]
Hi @NicoHaase 

Thanks for the suggestion - I agree.
