### ISSUE TITLE
Give suggestion for Xdebug 'coverage' not on

### ISSUE THREAD

**Issue by rkeet** [dvdoug/behat-code-coverage#2]
Related: https://github.com/dvdoug/behat-code-coverage/issues/1

Was debugging a bit as the throw error with message `No code coverage driver is available` is a bit non-descriptive when you've never thought about it ;) 

Suggestion: 

File: `src/Driver/Selector.php`
Line: 43

Change: 

```php
$driver = new Xdebug3Driver($filter);
```

to:

```php
try {
    $driver = new Xdebug3Driver($filter);
} catch (Xdebug3NotEnabledException) {
    throw new NoCodeCoverageDriverAvailableException('Xdebug 3 was found enabled, but "mode" does not include "coverage", did you forget to enable this?');
}
```

Subsequent required update to `NoCodeCoverageDriverAvailableException `: 

```php

final class NoCodeCoverageDriverAvailableException extends RuntimeException implements Exception
{
    private const DEFAULT_MESSAGE = 'No code coverage driver available';

    public function __construct(string $message = null)
    {
        parent::__construct($message ?? self::DEFAULT_MESSAGE);
    }
}
```

Suggested changes would make finding why it's not working (initially) easier. (Admittedly: I did do a "*doh*, that makes sense" after I found it :p )

Suggested changes would also allow the same for other coverage drivers to have similar messages with minimal effort (try/catch blocks).

---

If you would like some help doing such changes, let me know and I'll see if I can spare some time outside of work.

**Comment by dvdoug** [comment]
Hi @rkeet 

Thanks for the feature request. The bad news is that the files you've suggested changing don't belong to this project, they are part of [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage). The good news is that the next release of this library [will display](https://github.com/dvdoug/behat-code-coverage/commit/8cec1283bd853064755dbd6b7e8aded9f1f64294) the relevant exception message that php-code-coverage produces e.g. [Xdebug3NotEnabledException](https://github.com/sebastianbergmann/php-code-coverage/blob/9.2/src/Exception/Xdebug3NotEnabledException.php):

```
> vendor/bin/behat
No code coverage driver is available. XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
```
