### ISSUE TITLE
Optionally fail Behat run when coverage is below threshold

### ISSUE THREAD

**Issue by ttomdewit** [dvdoug/behat-code-coverage#5]
Hello :wave:,

First of all thank you very much for your hard work! I recently (re)started dabbling with Behat and was lucky enough to find this extension.

I would like to propose a feature request: optionally allow to fail tests below a certain threshold, similar to Infection with their `--min-msi` and `--min-covered-msi` options ([see their docs](https://infection.github.io/guide/command-line-options.html#min-msi)).

Is this something worth considering? If so I think I can give it a shot as PR the feature.

Thank you for your time!

**Comment by ttomdewit** [comment]
By using the following in the YAML file:

```yaml
reports:
  clover:
    target: .build/behat/clover.xml
```

it generates a nice `clover.xml` file. With the help of https://github.com/richardregeer/phpunit-coverage-check it's possible to get a percentage of coverage and allow the command to fail, without touching this very extension.

Part of my Makefile:

```makefile
behat:
	time ./vendor/bin/behat
behat-test-coverage: behat
	time ./vendor/bin/coverage-check .build/behat/clover.xml 100
```

**Comment by dvdoug** [comment]
Hi

Thanks for the suggestion, unfortunately I don't see a way of doing this inside Behat directly - the way the extension works is by hooking into various Behat events, however these are receive only - there's no way I'm aware of to control execution in any way.

The way you describe by having a post-Behat check on the result is the best that's possible so it's good you found it.
